services:
  account-management-api:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
    # env_file:
    #   - root/config/credentials.env
    volumes:
      - ./:/go/src/account-management
    container_name: account-management-api
    ports:
      - 3000:3000
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - account-management-postgres
  account-management-postgres:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: account-management-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=account_management
    volumes:
      - $PWD/sql/:/docker-entrypoint-initdb.d
