services:
  account-management-api:
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
    # env_file:
    #   - root/config/credentials.env
    volumes:
      - ./:/usr/local/go/src/account-management
    container_name: account-management-api
    ports:
      - 3000:3000
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
